// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAbHaHZHNNrshv-P06ny12XiEzlD1EMkM',
    appId: '1:53285433580:web:2ef00f06b1640efff775c9',
    messagingSenderId: '53285433580',
    projectId: 'fir-21312107',
    authDomain: 'fir-21312107.firebaseapp.com',
    storageBucket: 'fir-21312107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA70EBoFsjNhhNPcQeLHcJwHWMaz_Hougk',
    appId: '1:53285433580:android:caadf094db12b6c7f775c9',
    messagingSenderId: '53285433580',
    projectId: 'fir-21312107',
    storageBucket: 'fir-21312107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWD6n9PB1yB9lFrYEkLNp4TOYy8lOTPl4',
    appId: '1:53285433580:ios:b7e3d69fb438bc44f775c9',
    messagingSenderId: '53285433580',
    projectId: 'fir-21312107',
    storageBucket: 'fir-21312107.appspot.com',
    iosClientId: '53285433580-ajt6sr9gti1a9sh0n3f6v939hmilvegr.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWD6n9PB1yB9lFrYEkLNp4TOYy8lOTPl4',
    appId: '1:53285433580:ios:8a5e0d21f5468560f775c9',
    messagingSenderId: '53285433580',
    projectId: 'fir-21312107',
    storageBucket: 'fir-21312107.appspot.com',
    iosClientId: '53285433580-qvda0eiq7h01esqlmocgrbtns3gf4c3v.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet.RunnerTests',
  );
}
